### PR TITLE
Lockless implementation.

### PR DESCRIPTION
**Pull request by edwarnicke**

### CODE REVIEW

**Comment by edwarnicke** [comment]
# Lockless (#10)
```
BenchmarkAll/Performance/ConcurrentAsyncMapAccess-2         	 2762971	       409 ns/op
BenchmarkAll/Performance/ConcurrentSyncMapAccessTest-2      	 1000000	      1152 ns/op
BenchmarkAll/Performance/ExecutorAsync-2                    	 2751626	       424 ns/op
BenchmarkAll/Performance/ExecutorSync-2                     	 1686134	       719 ns/op
BenchmarkAll/Baselines/BaselineConcurrentAccess-2           	 5992564	       217 ns/op
BenchmarkAll/Baselines/BaselineSyncMapReadWrite-2           	 1000000	      1178 ns/op
BenchmarkAll/Tests/ASyncExec-2                              	 1316314	       908 ns/op
BenchmarkAll/Tests/SyncExec-2                               	 1605465	       769 ns/op
BenchmarkAll/Tests/ExecOrder1-2                             	 1000000	      1103 ns/op
BenchmarkAll/Tests/ExecOrder2-2                             	    4687	    272906 ns/op
BenchmarkAll/Tests/ExecOneAtATime-2                         	 2106320	       552 ns/op
BenchmarkAll/Tests/DataRace-2                               	   10000	    226585 ns/op
BenchmarkAll/Tests/NestedAsyncDeadlock-2                    	 4315280	       259 ns/op
```

# Batched Mutex (#9)
```
BenchmarkAll/Performance/ConcurrentAsyncMapAccess-2         	 2646840	       385 ns/op
BenchmarkAll/Performance/ConcurrentSyncMapAccessTest-2      	 1218146	       961 ns/op
BenchmarkAll/Performance/ExecutorAsync-2                    	 1322840	       941 ns/op
BenchmarkAll/Performance/ExecutorSync-2                     	 2016836	       574 ns/op
BenchmarkAll/Tests/ASyncExec-2                              	 1563158	       787 ns/op
BenchmarkAll/Tests/SyncExec-2                               	 1870597	       650 ns/op
BenchmarkAll/Tests/ExecOrder1-2                             	 1000000	      1421 ns/op
BenchmarkAll/Tests/ExecOrder2-2                             	    5556	    348508 ns/op
BenchmarkAll/Tests/ExecOneAtATime-2                         	 2234728	       636 ns/op
BenchmarkAll/Tests/DataRace-2                               	 1000000	      1682 ns/op
BenchmarkAll/Tests/NestedAsyncDeadlock-2                    	 4767248	       324 ns/op
```

**Comment by edwarnicke** [comment]
#9 wins.

**Comment by edwarnicke** [comment]
# New Run of Lockless (#10)

```
BenchmarkAll/Performance/ConcurrentAsyncMapAccess-2         	 2900077	       350 ns/op
BenchmarkAll/Performance/ConcurrentSyncMapAccessTest-2      	 1418464	       785 ns/op
BenchmarkAll/Performance/ExecutorAsync-2                    	 3257460	       346 ns/op
BenchmarkAll/Performance/ExecutorSync-2                     	 2324283	       526 ns/op
BenchmarkAll/Tests/ASyncExec-2                              	 1772445	       696 ns/op
BenchmarkAll/Tests/SyncExec-2                               	 2105456	       561 ns/op
BenchmarkAll/Tests/ExecOrder1-2                             	 1387534	       878 ns/op
BenchmarkAll/Tests/ExecOrder2-2                             	    6244	    207243 ns/op
BenchmarkAll/Tests/ExecOneAtATime-2                         	 2573847	       443 ns/op
BenchmarkAll/Tests/DataRace-2                               	   10000	    166704 ns/op
BenchmarkAll/Tests/NestedAsyncDeadlock-2                    	 5014328	       214 ns/op
```

# Mutex Batched (#9)

```
BenchmarkAll/Performance/ConcurrentAsyncMapAccess-2         	 2646840	       385 ns/op
BenchmarkAll/Performance/ConcurrentSyncMapAccessTest-2      	 1218146	       961 ns/op
BenchmarkAll/Performance/ExecutorAsync-2                    	 1322840	       941 ns/op
BenchmarkAll/Performance/ExecutorSync-2                     	 2016836	       574 ns/op
BenchmarkAll/Tests/ASyncExec-2                              	 1563158	       787 ns/op
BenchmarkAll/Tests/SyncExec-2                               	 1870597	       650 ns/op
BenchmarkAll/Tests/ExecOrder1-2                             	 1000000	      1421 ns/op
BenchmarkAll/Tests/ExecOrder2-2                             	    5556	    348508 ns/op
BenchmarkAll/Tests/ExecOneAtATime-2                         	 2234728	       636 ns/op
BenchmarkAll/Tests/DataRace-2                               	 1000000	      1682 ns/op
BenchmarkAll/Tests/NestedAsyncDeadlock-2                    	 4767248	       324 ns/op
```

**Review by denis-tingaikin — APPROVED** [review]
Looks great. It detects deadlocks and reduces using lock/unlock of mutex.

**Comment by edwarnicke** [comment]
I don't think this will be a good road to take.  Its much much slower on parallel use.  See the results from this benchmark below:

```
func ExecutorParallelAsyncBenchmark(b testing.TB, exec *serialize.Executor, count int) {
	start := make(chan struct{})
	for i := 0; i < count-1; i++ {
		go exec.AsyncExec(func() {<-start})
	}
	close(start)
	<-exec.AsyncExec(func() {})
}
```

# Lockless

BenchmarkAll/Performance/ExecutorParallelAsyncBenchmark-16         	   10000	    459005 ns/op

# Master

BenchmarkAll/Performance/ExecutorParallelAsyncBenchmark-16         	 1000000	      1433 ns/op

**Pull request closed without merging**
